api_id = "38498066"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         #)<@scaMmEr<
api_hash = "c9696114751feacdeb1b4487f5839a1a"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               #)sCaMMER^
bot_token = "7644668124:AAE3JLKyiKbWolr33InO5-QKk6lphqnu1UI"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #-=(ScAMMeR>
FORCE_CHANNEL = 'CinderellaReview'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #@_&ScAMmeR#<+
LOGS_CHANNEL = -1003597599758                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             #^ScAmmeR%%*
OWNER = 7385324642                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          #$^sCAmMer_
image = 'logo.jpg'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      #(SCammER-
MONGO_URI = ''                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             #<##sCAMmer$)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #<##sCAMmer$)
name = 'saksham'
OWNER_USERNAME = 'Ⓢⓐⓚⓢⓗⓐⓜ Ⓑⓗⓐⓘⓨⓐ'

START_TEXT="""
I'm Batch-Txt Extractor bot....!

🚀 Made By @sakshambhaiya🚀

Usage : First select the app listed below. ⤵️
"""
START_TEXT1="""
I'm Batch-Txt Extractor bot....!

🎯 Made By @sakshambhaiya 🎯
🔰  Now, select the course listed below. 📌
"""
START_TEXTCP="""
I'm CLASSPLUS Extractor bot....!

⤵️  Now, select the Option listed below. 🎯
"""
START_TEXTAPPX="""
I'm APPX Extractor bot....!

🔰  Now, select the Option listed below. 🎯
"""
START_TEXTCP1="""
I'm Going to Generate Auth Token....!

🎯  Now, select the Methods to Geneterate Classplus Auth Token. ✅
"""
HELP_TEXT="""
I'm Batch extractor bot...!
🚀Commands

/helper - For Extracting Txts.

⚠️ Save this id » @sakshambhaiya in case of Copyright infringement.
"""
